apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 637423167482.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 637423167482.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: f4c0ebc7
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
